version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/go/src/gobe/
  postgresdb:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  dbdata:
